# Generated by Django 4.2.7 on 2026-04-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_service_options_service_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_approved',
            field=models.BooleanField(default=False),
        ),
    ]
