# Generated by Django 4.2.7 on 2026-04-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_bookingslot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingslot',
            options={'ordering': ['service_date', 'service_time']},
        ),
        migrations.AlterUniqueTogether(
            name='bookingslot',
            unique_together={('service_date', 'service_time')},
        ),
        migrations.RemoveField(
            model_name='bookingslot',
            name='service',
        ),
    ]
